name: Check code style and typing

on: [push, pull_request, workflow_dispatch]
jobs:
  check-code-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Check formatting
        run: yarn check-format
        
  check-code-typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        working-directory: ./API
        run: yarn
        
      - name: Install GDevelop
        working-directory: ..
        run: git clone https://github.com/4ian/GDevelop && cd GDevelop/GDJS && yarn
      
      - name: Check types
        working-directory: ./API
        run: yarn ts

  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: cd API && yarn && cd ../Loader/webLoader && yarn && yarn add addons-linter 
        
      - name: Build webLoader
        working-directory: ./Loader/webLoader
        run: yarn import-api
        
      - name: Run mozilla addon linter
        working-directory: ./Loader/webLoader
        run: yarn addons-linter ./extension
