name: Check code style and typing

on: [push, pull_request, workflow_dispatch]
jobs:
  check-code-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Check formatting
        run: yarn check-format

  check-code-typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Check types
        working-directory: ./packages/API
        run: yarn ts

  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn && yarn lerna add addons-linter --scope=@gdmod/web-loader

      - name: Run mozilla addon linter
        working-directory: ./packages/web-loader
        run: yarn addons-linter ./extension
